version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/geo-data-slicer/
   file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  #BeforeInstall:
   #- location: delete.sh
    # timeout: 300
     #runas: ubuntu
  ApplicationStop:
   - location: stop.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: run.sh
     timeout: 400
     runas: ubuntu
