version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/geo-data-slicer/geo-data-slicer/
hooks:
  ApplicationStop:
   - location: scripts/stop
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
