const MAX_AREA_CONCURRENT_RUN = 200000000000; // in m2, 4x4 lonxlat = 197960531766
const CONCURRENT_SLICE_REQUEST = 5;

const WEATHER_FILE_TYPES = {
  grib: 'GRIB',
  json: 'JSON',
};

module.exports = {
  MAX_AREA_CONCURRENT_RUN,
  CONCURRENT_SLICE_REQUEST,
  WEATHER_FILE_TYPES,
};
