name: CI/CD Pipeline
on:
  push:
    branches:
      - develop
      - dev-test

jobs:
  deploy:
    name: Build image and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Init submodule to repo
        run: git submodule update --init

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Folder
        run: zip -r slicer-dev.zip ./data ./src ./operating_folder ./Dockerfile ./.Dockerignore ./.env.example ./*.sh ./*.js ./*.json ./*.yml

      - name: Upload to S3
        run: aws s3 cp slicer-dev.zip s3://syrf-dev-env-variables

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name geo-data-slicer-dev \
            --deployment-group-name slicercicdDeploymentgroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=syrf-dev-env-variables,bundleType=zip,key=slicer-dev.zip
