name: Prod Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build image and replace container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Init submodule to repo
        run: git submodule update --init

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Zip Folder
        run: zip -r slicer-prod.zip ./data ./src ./pyscripts ./Dockerfile ./.Dockerignore ./.env.example ./*.sh ./*.js ./*.json ./*.yml

      - name: Upload to S3
        run: aws s3 cp slicer-prod.zip s3://syrf-prod-env-variables

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name geo-data-slicer-prod \
            --deployment-group-name slicerDeploymentgroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=syrf-prod-env-variables,bundleType=zip,key=slicer-prod.zip
